# Generated by Django 2.2.6 on 2019-10-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20191005_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='subject',
            new_name='name',
        ),
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
