# Generated by Django 2.2.6 on 2019-10-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20191005_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AddField(
            model_name='topic',
            name='isclosed',
            field=models.BooleanField(default=False),
        ),
    ]
