# Generated by Django 2.2.6 on 2019-10-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20191023_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='isclosed',
            new_name='is_closed',
        ),
    ]
