# Generated by Django 2.2.6 on 2019-10-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_likedislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
