# Generated by Django 2.2.6 on 2019-11-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_likedislike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pk']},
        ),
    ]
