# Generated by Django 2.2.6 on 2019-11-13 17:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191113_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='empty-avatar.png', height_field='height_field', upload_to=accounts.models.upload_location, width_field='width_field'),
        ),
    ]
