# Generated by Django 2.2.6 on 2019-11-13 17:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191113_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='empty-avatar.png', height_field='height_field', null=True, upload_to=accounts.models.upload_location, width_field='width_field'),
        ),
    ]
